name: Bicep What-If

on:
  push:
    paths:
      - 'bicep/**'

env:
  bicep_rg: Lab

jobs:
  bicep:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2
        
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: run bicep create
        run: |
          cd bicep
          az deployment group create -f ./main.bicep -g ${{ env.bicep_rg }} --name deployment-bicep --mode Complete
      
      - name: Azure Logout
        run: |
          az logout

