name: Terraform Apply

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
    # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2
        with:
          terraform_version: 1.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: | 
          cd Workflow
          terraform init
      - name: Terraform Format
        run: | 
          cd Workflow
          terraform fmt -check
        continue-on-error: true

      - name: Terraform Apply
        run: | 
          cd Workflow
          terraform apply -auto-approve

      - name: Terraform Validate
        run: | 
          cd Workflow
          terraform validate -no-color


